name: CI

#controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
    sync-to-hub:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Add remote
          env:
            Hugging_Face: ${{ secrets.Hugging_Face }}
          run: git remote add space https://Prernak12:$Hugging_Face@huggingface.co/spaces/Prernaaa/Hugging_face_demo2
        - name: Push to hub
          env:
            Hugging_Face : ${{ secrets.Hugging_Face }}
          run: git push --force https://Prernak12:$Hugging_Face@huggingface.co/spaces/Prernaaa/Hugging_face_demo2 main
        
